/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brianhensel' at '4/17/17 8:26 PM' with Gradle 2.14.1
 *
 * @author brianhensel, @date 4/17/17 8:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
